include: package:lint/strict.yaml
linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    always_declare_return_types: true
    sort_pub_dependencies: false

analyzer:
  exclude:
    - "**/*.gql.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
