name: koyo
description: A Flutter utility library that enables faster development and less boilerplate for specific use cases.
version: 0.4.0
repository: https://github.com/timosg/koyo/tree/main
issue_tracker: https://github.com/timosg/koyo/issues
homepage: https://github.com/timosg/koyo

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^8.0.0
  internet_connection_checker_plus: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.0
  lint: ^2.0.0
  flutter_test:
    sdk: flutter
