name: koyo
description: Flutter utility library.
version: 0.1.0+1
homepage: https://www.wydget.de

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  internet_connection_checker_plus: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
