name: koyo
description: A Flutter utility library that enables faster development and less boilerplate for specific use cases.
version: 0.6.0
repository: https://github.com/timosg/koyo/tree/main
issue_tracker: https://github.com/timosg/koyo/issues
homepage: https://github.com/timosg/koyo

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  device_info_plus: ^11.5.0
  internet_connection_checker_plus: ^2.7.2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.0
  lint: ^2.0.0
  flutter_test:
    sdk: flutter
